apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone
  labels:
    app: devops-capstone
    namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: rollingUpdate
  template:
    metadata:
      labels:
        app: devops-capstone
    spec:
      containers:
        - image: khare123/cloud-devops-capstone
          imagePullPolicy: Always
          name: cloud-devops-capstone
          ports:
            - containerPort: 80
