kind: ReplicationController
apiVersion: v1
metadata:
  name: green
  labels:
      app: green
spec:
  replicas: 1
  selector:
    app: green
  template:
    metadata:
      labels:
        app: green
    spec:
        containers:
          - name: green
            image: khare123/cloud-devops-capstone
            ports: 
              - name: server
                containerPort: 80