kind: Service
apiVersion: v1
metadata:
  name: devops-capstone
  labels:
    app: devops-capstone
  spec:
    ports:
      - port: 80
        targetPort: 80
    selector:
      app: devops-capstone
    type: LoadBalancer